{% set name = "tf-keras" %}
{% set version = "2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tf_keras-{{ version }}.tar.gz
    sha256: ebf744519b322afead33086a2aba872245473294affd40973694f3eb7c7ad77d
  - fn: LICENSE
    url: https://raw.githubusercontent.com/keras-team/tf-keras/master/LICENSE
    sha256: 58d1e17ffe5109a7ae296caafcadfdbe6a7d176f0bc4ab01e12a689b0499d8bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.23
    - tensorflow >=2.17,<2.18

test:
  imports:
    - tf_keras
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://keras.io/
  dev_url: https://github.com/keras-team/tf-keras
  summary: Deep learning for humans.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/keras
